name: scamlab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_window_close: ^1.2.0
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  state_machine: ^3.0.1
  timer_flutter: ^0.2.3-beta
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
