services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: scamlab
      POSTGRES_USER: scamuser
      POSTGRES_PASSWORD: scampass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    networks:
      - scamlab-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scamuser -d scamlab"]
      interval: 5s
      timeout: 5s
      retries: 5

  # llm:
  #   image: localai/localai:latest-aio-gpu-nvidia-cuda-12
  #   ports:
  #     - "1234:8080"
  #   environment:
  #     - DEBUG=true
  #   volumes:
  #     - ./llm:/build/models:cached
  #   networks:
  #     - scamlab-net
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
  #     interval: 1m
  #     timeout: 20m
  #     retries: 5
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           count: 1
  #           capabilities: [gpu]

  quarkus-api:
    build:
      context: ../scamlab-server/
      dockerfile: ../scamlab-server/src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://scamuser:scampass@postgres:5432/scamlab
      QUARKUS_LLM_BASE_URL: http://llm:1234
      QUARKUS_HTTP_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - scamlab-net

  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../scamlab-client/build/web:/usr/share/nginx/html
    depends_on:
      - quarkus-api
    networks:
      - scamlab-net

volumes:
  postgres_data:

networks:
  scamlab-net: