services:
  postgres:
    image: postgres:17.4
    container_name: database
    environment:
      POSTGRES_DB: scamlab
      POSTGRES_USER: scamuser
      POSTGRES_PASSWORD: scampass
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scamlab-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scamuser -d scamlab"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  # llm:
  #   image: vllm/vllm-openai:latest
  #   container_name: llm
  #   model: 
  #     - google/gemma-2b
  #   volumes:
  #     - llm_models:/root/.cache/huggingface
  #   networks:
  #     - scamlab-net
    
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s

  quarkus-api:
    image: com646/scamlab-server
    container_name: api
    environment:
      QUARKUS_PROFILE: prod
    ports:
      - 8080:8080
    networks:
      - scamlab-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  scamlab-net: