version: '3.8'

services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: scamlab
      POSTGRES_USER: scamuser
      POSTGRES_PASSWORD: scampass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scamlab-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scamuser -d scamlab"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - scamlab-net
    command: ["ollama", "serve"]

  quarkus-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://scamuser:scampass@postgres:5432/scamlab
      QUARKUS_OLLAMA_BASE_URL: http://ollama:11434
      QUARKUS_HTTP_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - scamlab-net

  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./client/web-build:/usr/share/nginx/html
    depends_on:
      - quarkus-api
    networks:
      - scamlab-net

volumes:
  postgres_data:
  ollama_models:

networks:
  scamlab-net: